[build]
  functions = "functions"
  publish = "build" # Si tienes una carpeta build para tu frontend

[functions]
<<<<<<< HEAD
  directory = "functions"
=======
  directory = "functions"
>>>>>>> 9e3f7d5bf4d7d8439fe6074964ade0b6ba96caeb
